services:
  postgres:
    image: postgres:17
    container_name: subscriptions_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/subscriptions_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subs"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscriptions_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
 
volumes:
  postgres_data: